export const localidades = [
  { label: "Usaquén", value: 1 },
  { label: "Chapinero", value: 2 },
  { label: "Santa Fe", value: 3 },
  { label: "San Cristóbal", value: 4 },
  { label: "Usme", value: 5 },
  { label: "Tunjuelito", value: 6 },
  { label: "Bosa", value: 7 },
  { label: "Kennedy", value: 8 },
  { label: "Fontibón", value: 9 },
  { label: "Engativá", value: 10 },
  { label: "Suba", value: 11 },
  { label: "Barrios Unidos", value: 12 },
  { label: "Teusaquillo", value: 13 },
  { label: "Los Mártires", value: 14 },
  { label: "Antonio Nariño", value: 15 },
  { label: "Puente Aranda", value: 16 },
  { label: "La Candelaria", value: 17 },
  { label: "Rafael Uribe Uribe", value: 18 },
  { label: "Ciudad Bolívar", value: 19 },
  { label: "Sumapaz", value: 20 },
];

export const diasSemana = [
  { label: "Lunes", value: "Lunes" },
  { label: "Martes", value: "Martes" },
  { label: "Miércoles", value: "Miercoles" },
  { label: "Jueves", value: "Jueves" },
  { label: "Viernes", value: "Viernes" },
  { label: "Sábado", value: "Sábado" },
  { label: "Domingo", value: "Domingo" },
];

export const clasesSiniestro = [
  { label: "Choque", value: 1 },
  { label: "Atropello", value: 2 },
  { label: "Volcamiento", value: 3 },
  { label: "Caída de ocupante", value: 4 },
  { label: "Incendio", value: 5 },
  { label: "Otro", value: 6 },
  { label: "Autolesión", value: 7 },
];

export const disenosLugar = [
  { label: "Tramo de vía", value: 1 },
  { label: "Intersección", value: 2 },
  { label: "Vía peatonal", value: 3 },
  { label: "Paso elevado", value: 4 },
  { label: "Paso inferior", value: 5 },
  { label: "Paso a nivel", value: 6 },
  { label: "Glorieta", value: 7 },
  { label: "Puente", value: 8 },
  { label: "Vía troncal", value: 9 },
  { label: "Lote o predio", value: 10 },
  { label: "Cicloruta", value: 11 },
  { label: "Pontón", value: 12 },
  { label: "Túnel", value: 13 },
];

export const condicionesActor = [
  { label: "CONDUCTOR", value: "CONDUCTOR" },
  { label: "PEATON", value: "PEATON" },
  { label: "PASAJERO/ACOMPAÑANTE", value: "PASAJERO/ACOMPAÑANTE" },
  { label: "CICLISTA", value: "CICLISTA" },
  { label: "MOTOCICLISTA", value: "MOTOCICLISTA" },
];

export const clasesVehiculo = [
  { label: "Automóvil", value: 1 },
  { label: "Bus", value: 2 },
  { label: "Buseta", value: 3 },
  { label: "Camión/Furgon", value: 4 },
  { label: "Camioneta", value: 5 },
  { label: "Campero", value: 6 },
  { label: "Microbus", value: 7 },
  { label: "Tractocamion", value: 8 },
  { label: "Volqueta", value: 9 },
  { label: "Motocicleta", value: 10 },
  { label: "Bicicleta", value: 13 },
  { label: "Motocarro", value: 14 },
  { label: "Motociclo", value: 17 },
  { label: "Cuatrimoto", value: 24 },
  { label: "Bicitaxi", value: 28 },
];

export const serviciosVehiculo = [
  { label: "Oficial", value: 1 },
  { label: "Público", value: 2 },
  { label: "Particular", value: 3 },
  { label: "Diplomático", value: 4 },
];

export const modalidadesVehiculo = [
  { label: "Mixto", value: 1 },
  { label: "Carga - Extrapesada", value: 2 },
  { label: "Carga - Extradimensionada", value: 3 },
  { label: "Pasajeros - Colectivo", value: 4 },
  { label: "Pasajeros - Individual", value: 5 },
  { label: "Pasajeros - Especial escolar", value: 6 },
  { label: "Pasajeros - Especial turismo", value: 7 },
  { label: "Pasajeros - Especial asalariado", value: 8 },
  { label: "Pasajeros - Especial Ocasional", value: 9 },
  { label: "Pasajeros - Masivo", value: 10 },
  { label: "Carga-Pesada", value: 11 },
  { label: "Carga - Mercancia Peligrosa", value: 12 },
];

export const causasPrincipales = [
  { label: "Transportar otra persona o cosas (ciclista o motociclista)", value: 90 },
  { label: "No conducir en horcajadas (ciclista o motociclista)", value: 91 },
  { label: "No sujetar los manubrios (ciclista o motociclista)", value: 92 },
  { label: "Transitar distante de la acera u orilla de la calzada (ciclista o motociclista)", value: 93 },
  { label: "Circular por calzadas destinadas a buses y busetas (ciclista o motociclista)", value: 94 },
  { label: "Transitar uno al lado del otro (ciclista o motociclista)", value: 95 },
  { label: "Sujetarse a otro vehículo (ciclista o motociclista)", value: 96 },
  { label: "Transitar por vías prohibidas (ciclista o motociclista)", value: 97 },
  { label: "Transitar entre vehículos (ciclista o motociclista)", value: 98 },
  { label: "No hacer uso de señales reflectivas (ciclista o motociclista)", value: 99 },
  { label: "Adelantar en curva (conductor en general)", value: 101 },
  { label: "Adelantar por la derecha (conductor en general)", value: 102 },
  { label: "Adelantar cerrando (conductor en general)", value: 103 },
  { label: "Adelantar invadiendo vía (conductor en general)", value: 104 },
  { label: "Adelantar en zona prohibida (conductor en general)", value: 105 },
  { label: "Adelantar invadiendo carril del mismo sentido en zigzag (conductor en general)", value: 106 },
  { label: "Aprovisionamiento indebido (conductor en general)", value: 107 },
  { label: "Carga sobresaliente sin señales (conductor en general)", value: 108 },
  { label: "Defectos físicos y psíquicos (conductor en general)", value: 109 },
  { label: "Exceso en horas de conducción (conductor en general)", value: 110 },
  { label: "Dejar obstáculos en la vía (conductor en general)", value: 111 },
  { label: "Desobedecer señales (conductor en general)", value: 112 },
  { label: "Desobedecer al agente (conductor en general)", value: 113 },
  { label: "Embriaguez aparente (conductor en general)", value: 114 },
  { label: "Embriaguez o droga (conductor en general)", value: 115 },
  { label: "Exceso de velocidad (conductor en general)", value: 116 },
  { label: "Explosivos o similares con pasajeros (conductor en general)", value: 117 },
  { label: "Falta de mantenimiento mecánico (conductor en general)", value: 118 },
  { label: "Frenar bruscamente (conductor en general)", value: 119 },
  { label: "Pasajeros obstruyendo el conductor (conductor en general)", value: 120 },
  { label: "No mantener distancia de seguridad (conductor en general)", value: 121 },
  { label: "Girar bruscamente (conductor en general)", value: 122 },
  { label: "No respetar prelación de intersecciones o giros (conductor en general)", value: 123 },
  { label: "No cambiar luces (conductor en general)", value: 124 },
  { label: "Estacionar sin seguridad (conductor en general)", value: 125 },
  { label: "Animales en la vía (conductor en general)", value: 126 },
  { label: "Transitar en contravía (conductor en general)", value: 127 },
  { label: "Recoger o dejar pasajeros sobre la calzada (conductor en general)", value: 128 },
  { label: "Transportar pasajeros en la parte exterior (conductor en general)", value: 129 },
  { label: "Transitar sin luces (conductor en general)", value: 130 },
  { label: "Salirse de la calzada (conductor en general)", value: 131 },
  { label: "No respetar prelación (conductor en general)", value: 132 },
  { label: "Subirse al andén o vías peatonales (conductor en general)", value: 133 },
  { label: "Reverso imprudente (conductor en general)", value: 134 },
  { label: "Remolque sin precaución (conductor en general)", value: 135 },
  { label: "Incendio por reparación indebida (conductor en general)", value: 136 },
  { label: "Falta de señales en vehículo varado (conductor en general)", value: 137 },
  { label: "Incendio por reparación indebida (conductor en general)", value: 138 },
  { label: "Impericia en el manejo (conductor en general)", value: 139 },
  { label: "Transitar sin los dispositivos luminosos de detención (conductor en general)", value: 140 },
  { label: "Vehículo mal estacionado (conductor en general)", value: 141 },
  { label: "Semáforo en rojo (conductor en general)", value: 142 },
  { label: "Poner en marcha un vehículo sin precauciones (conductor en general)", value: 143 },
  { label: "Carga sobresaliente sin autorización (conductor en general)", value: 144 },
  { label: "Arrancar sin precaución (conductor en general)", value: 145 },
  { label: "Realizar giro en \"u\" (conductor en general)", value: 146 },
  { label: "Conducir vehículo sin adaptaciones (conductor en general)", value: 147 },
  { label: "Exceso de peso (conductor en general)", value: 148 },
  { label: "Reparar vehículo en vía publica (conductor en general)", value: 149 },
  { label: "Impartir enseñanza automovilística sin autorización (conductor en general)", value: 150 },
  { label: "Transporte de carga sin seguridad (conductor en general)", value: 151 },
  { label: "Dejar o recoger pasajeros en sitios no demarcados (conductor en general)", value: 152 },
  { label: "No portar espejos (conductor en general)", value: 153 },
  { label: "Transitar con las puertas abiertas (conductor en general)", value: 154 },
  { label: "Cargue o descargue en horas o sitios prohibidos (conductor en general)", value: 155 },
  { label: "Transportar  pasajeros en vehículos de carga (conductor en general)", value: 156 },
  { label: "Otra (conductor en general)", value: 157 },
  { label: "Fallas en las llantas (vehículo)", value: 201 },
  { label: "Fallas en los frenos (vehículo)", value: 202 },
  { label: "Fallas en dirección (vehículo)", value: 203 },
  { label: "Fallas en luces direccionales (vehículo)", value: 204 },
  { label: "Fallas en luces de frenos (vehículo)", value: 205 },
  { label: "Fallas en luces delanteras (vehículo)", value: 206 },
  { label: "Falla en luces posteriores (vehículo)", value: 207 },
  { label: "Falla en pito (vehículo)", value: 208 },
  { label: "Falla en el exosto y gases en el interior  del veh (vehículo)", value: 209 },
  { label: "Fallas en el limpia brisas (vehículo)", value: 210 },
  { label: "Falla en el sistema eléctrico (vehículo)", value: 211 },
  { label: "Falla en las puertas (vehículo)", value: 212 },
  { label: "Ausencia o deficiencia de espejos retrovisores (vehículo)", value: 213 },
  { label: "Vidrios en mal estado (vehículo)", value: 214 },
  { label: "Tanque de combustible mal ubicado (vehículo)", value: 216 },
  { label: "Otra (vehículo)", value: 217 },
  { label: "Ausencia total o parcial de señales (vía)", value: 301 },
  { label: "Ausencia o deficiencia de demarcación (vía)", value: 302 },
  { label: "Superficie lisa (vía)", value: 303 },
  { label: "Superficie húmeda (vía)", value: 304 },
  { label: "Obstáculo en la vía (vía)", value: 305 },
  { label: "Huecos (vía)", value: 306 },
  { label: "Dejar o movilizar semovientes en la vía (vía)", value: 307 },
  { label: "Otras (vía)", value: 308 },
  { label: "Pasar semáforo en rojo (peatón)", value: 401 },
  { label: "Salir por delante de un vehículo (peatón)", value: 402 },
  { label: "Transitar por la derecha en vías rurales (peatón)", value: 403 },
  { label: "Transitar por la calzada (peatón)", value: 404 },
  { label: "Jugar en la vía (peatón)", value: 405 },
  { label: "Cruzar en diagonal (peatón)", value: 406 },
  { label: "Pararse sobre la calzada (peatón)", value: 407 },
  { label: "Cruzar en curva (peatón)", value: 408 },
  { label: "Cruzar sin observar (peatón)", value: 409 },
  { label: "Cruzar en estado de embriaguez (peatón)", value: 410 },
  { label: "Otras (peatón)", value: 411 },
  { label: "Viajar colgado o en los estribos (pasajero o acompañante)", value: 501 },
  { label: "Descender o subir del vehículo en marcha (pasajero o acompañante)", value: 502 },
  { label: "Pasajero embriagado (pasajero o acompañante)", value: 503 },
  { label: "Viajar a la izquierda del conductor (pasajero o acompañante)", value: 504 },
  { label: "Niños en asiento delantero (pasajero o acompañante)", value: 505 },
  { label: "Otra (pasajero o acompañante)", value: 506 },
];